# -*- coding: utf-8 -*-
"""soal_02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CDImuGjGdW_hMzOYLHEe5ULqq3QnW0YI

Visualisasi Grafik Nilai Mahasiswa
"""

import matplotlib.pyplot as plt

nilai = []

print("=== INPUT NILAI MAHASISWA ===")

# input data
for i in range(10):
    n = int(input("Masukkan nilai mahasiswa ke-" + str(i+1) + ": "))
    nilai.append(n)

# mencari nilai tertinggi dan terendah
tertinggi = nilai[0]
terendah = nilai[0]

for i in range(len(nilai)):
    if nilai[i] > tertinggi:
        tertinggi = nilai[i]

    if nilai[i] < terendah:
        terendah = nilai[i]

# menghitung kelulusan
lulus = 0
for i in range(len(nilai)):
    if nilai[i] >= 60:
        lulus = lulus + 1

tidak_lulus = len(nilai) - lulus

# grafik nilai tertinggi dan terendah
data_nilai = [tertinggi, terendah]
label_nilai = ["Tertinggi", "Terendah"]

plt.bar(label_nilai, data_nilai)
plt.title("Grafik Nilai Tertinggi dan Terendah")
plt.ylabel("Nilai")
plt.show()

# grafik kelulusan
data_kelulusan = [lulus, tidak_lulus]
label_kelulusan = ["Lulus", "Tidak Lulus"]

plt.bar(label_kelulusan, data_kelulusan)
plt.title("Grafik Kelulusan Mahasiswa")
plt.ylabel("Jumlah Mahasiswa")
plt.show()