# -*- coding: utf-8 -*-
"""Soal_01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PBfmTPiJIKoN5k4gMFJ0MiHXbaKM0zpJ

Sistem Pengelolaan Nilai Mahasiswa menggunakan Array
"""

# definisi array kosong
nilai = []

print("=== INPUT NILAI MAHASISWA ===")

# input 10 nilai mahasiswa
for i in range(10):
    n = int(input("Masukkan nilai mahasiswa ke-" + str(i+1) + ": "))
    nilai.append(n)

# tampilkan array
print("\nArray Nilai Mahasiswa:", nilai)

# mencari nilai tertinggi
tertinggi = nilai[0]
for i in range(len(nilai)):
    if nilai[i] > tertinggi:
        tertinggi = nilai[i]

# mencari nilai terendah
terendah = nilai[0]
for i in range(len(nilai)):
    if nilai[i] < terendah:
        terendah = nilai[i]

# menghitung rata-rata
total = 0
for i in range(len(nilai)):
    total = total + nilai[i]

rata = total / len(nilai)

# menghitung jumlah mahasiswa lulus
lulus = 0
for i in range(len(nilai)):
    if nilai[i] >= 60:
        lulus = lulus + 1

tidak_lulus = len(nilai) - lulus

# output hasil
print("\nNilai tertinggi :", tertinggi)
print("Nilai terendah :", terendah)
print("Rata-rata nilai :", rata)
print("Jumlah mahasiswa lulus :", lulus)
print("Jumlah mahasiswa tidak lulus :", tidak_lulus)